project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd 
        text: About
      - href: projects.qmd
        text: Lab
      - href: labs.qmd
        text: Presentations
      - href: presentations.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

